name: Foxy API Gateway CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  cache-warmup:
    name: Cache Warmup
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-warmup-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-warmup-
          ${{ runner.os }}-cargo-

    - name: Cache coverage tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-llvm-cov
          ~/.cargo/bin/cargo-tarpaulin
        key: ${{ runner.os }}-coverage-tools-warmup-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-coverage-tools-warmup-
          ${{ runner.os }}-coverage-tools-

    - name: Cache cargo-audit
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-audit
        key: ${{ runner.os }}-cargo-audit-warmup-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-warmup-
          ${{ runner.os }}-cargo-audit-

    - name: Warm up dependency cache
      run: |
        # Build dependencies only to warm up cache
        cargo build --lib --bins
        cargo build --tests

    - name: Warm up tool cache
      run: |
        # Install tools if not cached
        if ! command -v cargo-llvm-cov &> /dev/null; then
          cargo install cargo-llvm-cov
        fi
        if ! command -v cargo-tarpaulin &> /dev/null; then
          cargo install cargo-tarpaulin
        fi
        if ! command -v cargo-audit &> /dev/null; then
          cargo install cargo-audit
        fi

        # Pre-install llvm-tools-preview component for coverage
        # Handle potential conflicts gracefully
        rustup component add llvm-tools-preview || echo "llvm-tools-preview already installed or handled"

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: cache-warmup
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          # - nightly
        include:
          - rust: stable
            coverage: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ matrix.rust }}-
          ${{ runner.os }}-cargo-

    - name: Cache coverage tools
      if: matrix.coverage
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-llvm-cov
          ~/.cargo/bin/cargo-tarpaulin
        key: ${{ runner.os }}-coverage-tools-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-coverage-tools-

    - name: Install coverage tools
      if: matrix.coverage
      run: |
        # Only install if not cached
        if ! command -v cargo-llvm-cov &> /dev/null; then
          cargo install cargo-llvm-cov
        fi
        if ! command -v cargo-tarpaulin &> /dev/null; then
          cargo install cargo-tarpaulin
        fi

        # Ensure llvm-tools-preview is available (should be cached from warmup)
        # Handle potential conflicts gracefully
        rustup component add llvm-tools-preview || echo "llvm-tools-preview already installed or handled"

    # - name: Check formatting
    #   run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --lib --bins -- -D warnings

    - name: Build
      run: cargo build --verbose

    - name: Run unit tests
      run: cargo test --lib --verbose

    - name: Run integration tests
      run: cargo test --test '*' --verbose

    - name: Run benchmarks
      run: cargo bench --verbose
      continue-on-error: true

    - name: Generate coverage report
      if: matrix.coverage
      run: |
        # Generate LCOV formats for comprehensive coverage reporting
        mkdir coverage
        cargo llvm-cov --lcov --output-path coverage/lcov.info \
          --ignore-filename-regex 'benches/.*'

    - name: Upload coverage to Codecov
      if: matrix.coverage
      uses: codecov/codecov-action@v5
      with:
        files: coverage/lcov.info
        fail_ci_if_error: true

    - name: Upload coverage artifacts
      if: matrix.coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/

  security:
    name: Security Audit
    runs-on: ubuntu-latest
    needs: cache-warmup
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-security-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-security-

    - name: Cache cargo-audit
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-audit
        key: ${{ runner.os }}-cargo-audit-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-

    - name: Install cargo-audit
      run: |
        # Only install if not cached
        if ! command -v cargo-audit &> /dev/null; then
          cargo install cargo-audit
        fi

    - name: Run security audit
      run: cargo audit

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          foxy-io/foxy:latest
          foxy-io/foxy:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [test, security, docker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-release-
          ${{ runner.os }}-cargo-

    - name: Build release binary
      run: cargo build --release

    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/foxy
          target/release/foxy.exe
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-gates:
    name: Quality Gates
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-quality-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-quality-
          ${{ runner.os }}-cargo-

    - name: Cache coverage tools
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/cargo-llvm-cov
        key: ${{ runner.os }}-coverage-tools-quality-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-coverage-tools-quality-
          ${{ runner.os }}-coverage-tools-

    - name: Cache cargo-audit
      uses: actions/cache@v4
      with:
        path: ~/.cargo/bin/cargo-audit
        key: ${{ runner.os }}-cargo-audit-quality-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-audit-quality-
          ${{ runner.os }}-cargo-audit-

    - name: Install coverage tools
      run: |
        # Only install if not cached
        if ! command -v cargo-llvm-cov &> /dev/null; then
          cargo install cargo-llvm-cov
        fi

        # Ensure llvm-tools-preview is available (should be cached from warmup)
        # Handle potential conflicts gracefully
        rustup component add llvm-tools-preview || echo "llvm-tools-preview already installed or handled"

    - name: Generate coverage report
      run: |
        cargo llvm-cov --json --output-path coverage.json \
          --ignore-filename-regex 'benches/.*'

    - name: Check coverage threshold
      run: |
        COVERAGE=$(jq '.data[0].totals.lines.percent' coverage.json)
        echo "Current coverage: $COVERAGE%"
        
        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "Coverage $COVERAGE% is below minimum threshold of 90%"
          exit 1
        fi
        
        echo "Coverage check passed: $COVERAGE%"

    - name: Performance regression check
      run: |
        # Run benchmarks and compare with baseline
        cargo bench -- --output-format json > bench_results.json
        
        # This would typically compare against stored baseline results
        echo "Performance check completed"
        
    - name: Dependency vulnerability check
      run: |
        # Only install if not cached
        if ! command -v cargo-audit &> /dev/null; then
          cargo install cargo-audit
        fi
        cargo audit --deny warnings
